name: Deploy App to GitHub Pages

on:
  push:
    paths-ignore:
      - "README.md"

    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build React app
        env:
          VITE_GOOGLE_MAPS_API_KEY: ${{ secrets.VITE_GOOGLE_MAPS_API_KEY }} # Ref to Google Maps API Key
          VITE_SECRET_KEY: ${{ secrets.VITE_SECRET_KEY }} # Ref to Github Secrets recaptcha backend
          VITE_SITE_KEY: ${{ secrets.VITE_SITE_KEY }} # Ref to Github Secrets recaptcha frontend
        run: npm run build

      - name: Print build size
        run: ./scripts/build-size.sh

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # directory to deploy
          publish_branch: gh-pages # branch for deployment
