name: Deploy App to GitHub Pages

on:
  push:
    branches:
      - main # Trigger deployment on push to the main branch. Change if necessary.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Ensure this matches your project’s Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build React app
        env:
          VITE_GOOGLE_MAPS_API_KEY: ${{ secrets.VITE_GOOGLE_MAPS_API_KEY }} # Ref to Github Secrets
          SECRET_KEY: ${{ secrets.SECRET_KEY }} # Ref to Github Secrets recaptcha backend
          SITE_KEY: ${{ secrets.SITE_KEY }} # Ref to Github Secrets recaptcha frontend
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # directory to deploy
          publish_branch: gh-pages # branch for deployment
